### ISSUE TITLE
Parse error with Pspace warrior

### ISSUE THREAD

**Issue by conradj** [gareththegeek/corewar#117]
Grabbed the top [Pspace warrior](https://users.obs.carnegiescience.edu/birk/COREWAR/PSPACE/HILL/sunset.red) from [here](https://users.obs.carnegiescience.edu/birk/COREWAR/PSPACE/hill_rec.html).

And get parser errors:

```
PARSE RESULT
[74 , 12] ERROR: Expected opcode, got '.A'
[75 , 9] WARNING: Redefinition of label 'ldp', original definition will be used
[75 , 12] ERROR: Expected opcode, got '.BA'
[77 , 12] ERROR: Expected opcode, got '.B'
```

Get similar errors with others on that list too.

**Comment by gareththegeek** [comment]
P Space is not currently supported - I think parser errors need to be improved.  One improvement is probably some kind of primitive source mapping so that the error refers to code the user wrote rather than partially generated output code e.g. .A was not explicitly written by the user but generated as part of the parse process.

I would also be nice if the parser could detect opcodes which are not part of the currently selected spec and give a friendlier message.

I think I will raise some new issues for these and close this one down when I get time.

**Comment by gareththegeek** [comment]
Succeeded by #125 #127 #128
