### ISSUE TITLE
How to handle multiple actions at a single address per step

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar#40]
Looking at the simulator step, there are some times where the same address is referenced multiple times by an instruction.

1. Is this intended and possible? (I presume yes, which is why the step pushes to a queue and then those are processed one by one)
2. Would is be possible / sensible to resolve these multiple instructions before trying to apply them to the UI. At the moment I'm at a place where I'm trying to decide how best to render different the instructions action on an address and having composites seems a) a pain b) less performant. Are there tons of permutations? or would this be feasible do you think?

**Comment by gareththegeek** [comment]
I think the simplest thing to do is have writes take precedence over reads so if the same address is read from and written to in one step, the address should show write access.

As we discussed, I think execution should be handled separately from read/writes as execution reflects the state in the warrior/task tree structure rather than the state in the core structure.

**Comment by gareththegeek** [comment]
Raised #44 to handle reduce number of read events raised, this should remove the need to consider precedence.
