### ISSUE TITLE
Warriors within tasks seem empty

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar#41]
I've got the project publishing the core access events to the UI and the UI logging those.

When I step, I never seem to see the whole warrior populated, is this just an oversight? or a bug? 

![image](https://user-images.githubusercontent.com/1190042/33039718-cf8d0ca4-ce30-11e7-97c7-9a095e7acb84.png)

**Comment by gareththegeek** [comment]
This may not be an issue because once the warrior is loaded into core, the instructions are no longer required.  The only data that is required is the warrior's metadata (name, author etc.) and the list of tasks, each with an `instructionPointer`.

It is probably worth investigating at some point but I am not convinced it is a problem and it may be by design - I can't remember!

**Comment by dougajmcdonald** [comment]
Sounds legit! I think I'll find out if it's an issue when trying to mirror the warriors on the client

**Comment by gareththegeek** [comment]
The instruction array was redundant so I have removed it - #49 (it wasn't actually in the corresponding interface).  The others are blank because the warriors metadata hasn't been populated.  Try parsing a warrior like this:
```
;name MyWarrior
;author gareththegeek
;strategy Win!
```
and you should see the name, author and strategy fields populated correectly.
