### ISSUE TITLE
Sporadic lock ups

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar#68]
I've seen a number of odd lock ups when certain warriors are loaded at the point the simulator is initialised.

I don't see any errors from anywhere but the lock seems to nail chrome.

Requires investigation.

**Comment by gareththegeek** [comment]
Is it reproduceable?  Is there a particular warrior which breaks it?

**Comment by dougajmcdonald** [comment]
Working on that! Just a placeholder ATM. It seems to be after I've already 'run' a match.
I think the steps complete but the pubsub fails to deliver 80k ish messages in a few seconds causing a big ass lag. I'll show you tomorrow

**Comment by gareththegeek** [comment]
Is the pubsub asynchronous then?  I would have throught any delay in the pubsub would delay the run routine...

**Comment by dougajmcdonald** [comment]
I'm not sure it is which is, or if it is it's not fast enough to keep up with the core...or it is and the UI isn't responding to the messages fast enough. I made the run method return a promise as the setTimeout wasn't working as I wanted.

Generally what I see is:

- Run
- UI updates to show the data access for the first 60 or so cycles
- Promise resolved from run showing 80000 cycles completed (in a couple of seconds)
- Console trying to log another 79000 events 
- Slowdown
- Possibly never finishes which may be why the second run / initialise often seems to lock up

**Comment by dougajmcdonald** [comment]
I can confirm that the pubsub is async, so it must be the consumer not processing things fast enough.

I can probably tweak the component updates to batch changes and have a bit more a dig to figure out what is happening

**Comment by dougajmcdonald** [comment]
`getValidAddress`

**Comment by gareththegeek** [comment]
Figured out what causes the infinite loop, although I don't understand why it doesn't happen every time.  Not only do you need to set the `minSeparation` to 1, you also need to reduce the `instructionLimit`.  The logic is that two warriors must be at least `minSeparation + instructionLimit` apart.  The default `instructionLimit` is 100 so this makes it impossible to place a warrior in a core of size 64.

As I say, unsure why this ever worked - I'll look at making the core library more defensive so that it will reject invalid settings.

**Comment by dougajmcdonald** [comment]
Amazin' I was just digging into the numbers to take a look at that side of things, saved me the work

**Comment by gareththegeek** [comment]
Should be resoved by #74
